import { Ticket } from "@/types/ticket";

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "t1",
    ticketNumber: "TICK-1024",
    title: "VPN connection dropping repeatedly",
    description:
      "Whenever I connect to the remote corporate server from home, the VPN connection drops every 5-10 minutes with error code SEC_ERROR_PEER_INITIALIZATION_FAILED. This interrupts active SSH sessions and database queries.",
    category: "Network & VPN",
    priority: "HIGH",
    status: "IN_PROGRESS",
    creatorName: "Abebe Tesfaye",
    assigneeId: "agent_101",
    department: "Network & VPN",
    createdAt: "2026-07-20T09:30:00Z",
    dueAt: "2026-07-22T17:00:00Z",
    updatedAt: "2026-07-21T10:15:00Z",
    comments: [
      {
        id: "c1",
        authorName: "Abebe Tesfaye",
        authorRole: "EMPLOYEE",
        timestamp: "2026-07-20T09:30:00Z",
        content: "I tried restarting my home router and clearing DNS cache, but the issue persists.",
      },
      {
        id: "c2",
        authorName: "Sarah Connor",
        authorRole: "AGENT",
        timestamp: "2026-07-21T10:15:00Z",
        content:
          "Investigating the gateway auth logs. It looks like a timeout issue on gateway-us-east. Please verify your OpenVPN client version.",
      },
    ],
    history: [
      {
        id: "h1",
        timestamp: "2026-07-20T09:30:00Z",
        title: "Ticket Created",
        description: "Ticket submitted by Abebe Tesfaye.",
        type: "CREATED",
      },
      {
        id: "h2",
        timestamp: "2026-07-20T11:00:00Z",
        title: "Priority Updated",
        description: "Priority set to HIGH by Support Agent.",
        type: "PRIORITY",
      },
      {
        id: "h3",
        timestamp: "2026-07-21T10:15:00Z",
        title: "Status Changed to IN_PROGRESS",
        description: "Agent Sarah Connor began active investigation.",
        type: "STATUS",
      },
    ],
  },
  {
    id: "t2",
    ticketNumber: "TICK-1028",
    title: "Request for Figma Enterprise License",
    description:
      "Newly onboarded Senior Product Designer in the Marketing team requires a Figma Enterprise editor license for the upcoming Q3 rebranding project.",
    category: "Software & SaaS",
    priority: "MEDIUM",
    status: "OPEN",
    creatorName: "Alice Smith",
    assigneeId: "agent_101",
    department: "Software & SaaS",
    createdAt: "2026-07-21T08:00:00Z",
    dueAt: "2026-07-23T17:00:00Z",
    updatedAt: "2026-07-21T08:00:00Z",
    comments: [
      {
        id: "c3",
        authorName: "Alice Smith",
        authorRole: "EMPLOYEE",
        timestamp: "2026-07-21T08:00:00Z",
        content: "Manager approval from Mark Johnson is attached to the internal request portal.",
      },
    ],
    history: [
      {
        id: "h4",
        timestamp: "2026-07-21T08:00:00Z",
        title: "Ticket Created",
        description: "License request submitted by Alice Smith.",
        type: "CREATED",
      },
    ],
  },
  {
    id: "t3",
    ticketNumber: "TICK-1011",
    title: "Monitors flickering on USB-C Docking Station",
    description:
      "Dual 4K monitors flicker black for 2-3 seconds whenever the laptop resumes from sleep mode or when plugging in power supply.",
    category: "Hardware",
    priority: "LOW",
    status: "RESOLVED",
    creatorName: "Bob Martin",
    assigneeId: "agent_101",
    department: "Hardware",
    createdAt: "2026-07-18T14:00:00Z",
    dueAt: "2026-07-19T18:00:00Z",
    updatedAt: "2026-07-20T16:45:00Z",
    comments: [
      {
        id: "c4",
        authorName: "Sarah Connor",
        authorRole: "AGENT",
        timestamp: "2026-07-19T09:15:00Z",
        content: "We have dispatched replacement DisplayPort 1.4 cables to desk #402.",
      },
      {
        id: "c5",
        authorName: "Bob Martin",
        authorRole: "EMPLOYEE",
        timestamp: "2026-07-20T15:30:00Z",
        content: "The new cables arrived and DisplayLink firmware updated. Flickering is completely gone now! Thanks!",
      },
      {
        id: "c6",
        authorName: "Sarah Connor",
        authorRole: "AGENT",
        timestamp: "2026-07-20T16:45:00Z",
        content: "Glad to hear that! Marking ticket as resolved.",
      },
    ],
    history: [
      {
        id: "h5",
        timestamp: "2026-07-18T14:00:00Z",
        title: "Ticket Created",
        description: "Issue reported by Bob Martin.",
        type: "CREATED",
      },
      {
        id: "h6",
        timestamp: "2026-07-19T09:00:00Z",
        title: "Status Changed to IN_PROGRESS",
        description: "Hardware diagnostics initiated.",
        type: "STATUS",
      },
      {
        id: "h7",
        timestamp: "2026-07-20T16:45:00Z",
        title: "Status Changed to RESOLVED",
        description: "Hardware replacement and firmware update completed.",
        type: "STATUS",
      },
    ],
  },
  {
    id: "t4",
    ticketNumber: "TICK-0992",
    title: "Email delivery failure to external partner domain",
    description:
      "All outgoing emails sent to @partnerdomain.com bounce back immediately with SMTP 550 5.7.1 Unauthenticated mail error. Affecting critical client communications.",
    category: "Email & Communication",
    priority: "CRITICAL",
    status: "CLOSED",
    creatorName: "Rachel Green",
    assigneeId: "agent_101",
    department: "Email & Communication",
    createdAt: "2026-07-15T11:20:00Z",
    dueAt: "2026-07-16T17:00:00Z",
    updatedAt: "2026-07-16T12:00:00Z",
    comments: [
      {
        id: "c7",
        authorName: "Rachel Green",
        authorRole: "EMPLOYEE",
        timestamp: "2026-07-15T11:22:00Z",
        content: "Urgent! Contract negotiations are stalled due to bounce-backs.",
      },
      {
        id: "c8",
        authorName: "Sarah Connor",
        authorRole: "AGENT",
        timestamp: "2026-07-15T14:30:00Z",
        content: "Identified SPF/DKIM misconfiguration in DNS TXT record during domain migration. Updating DNS entries now.",
      },
      {
        id: "c9",
        authorName: "Sarah Connor",
        authorRole: "AGENT",
        timestamp: "2026-07-16T10:00:00Z",
        content: "DNS propagation complete and test message successfully delivered.",
      },
      {
        id: "c10",
        authorName: "Rachel Green",
        authorRole: "EMPLOYEE",
        timestamp: "2026-07-16T11:45:00Z",
        content: "Confirmed! Partner received the emails. Everything working.",
      },
    ],
    history: [
      {
        id: "h8",
        timestamp: "2026-07-15T11:20:00Z",
        title: "Ticket Created",
        description: "Issue submitted by Rachel Green.",
        type: "CREATED",
      },
      {
        id: "h9",
        timestamp: "2026-07-15T11:25:00Z",
        title: "Priority Escalated to CRITICAL",
        description: "Escalated due to business impact.",
        type: "PRIORITY",
      },
      {
        id: "h10",
        timestamp: "2026-07-15T14:00:00Z",
        title: "Status Changed to IN_PROGRESS",
        description: "DNS authentication fix in progress.",
        type: "STATUS",
      },
      {
        id: "h11",
        timestamp: "2026-07-16T10:00:00Z",
        title: "Status Changed to RESOLVED",
        description: "Mail bounce issue resolved.",
        type: "STATUS",
      },
      {
        id: "h12",
        timestamp: "2026-07-16T12:00:00Z",
        title: "Ticket Closed",
        description: "Ticket automatically closed after user confirmation.",
        type: "STATUS",
      },
    ],
  },
  {
    id: "t5",
    ticketNumber: "TICK-1035",
    title: "Database connection timeout in Staging Environment",
    description:
      "Staging API cluster cannot reach PostgreSQL read replica due to maximum connection pool saturation. Needs immediate pool scale-up or query termination.",
    category: "Database & Infrastructure",
    priority: "CRITICAL",
    status: "OPEN",
    creatorName: "David Chen",
    assigneeId: "agent_101",
    department: "Database & Infrastructure",
    createdAt: "2026-07-22T08:15:00Z",
    dueAt: "2026-07-22T20:00:00Z",
    updatedAt: "2026-07-22T08:15:00Z",
    comments: [
      {
        id: "c11",
        authorName: "David Chen",
        authorRole: "EMPLOYEE",
        timestamp: "2026-07-22T08:16:00Z",
        content: "Blocking QA team from completing regression test suite before production deployment.",
      },
    ],
    history: [
      {
        id: "h13",
        timestamp: "2026-07-22T08:15:00Z",
        title: "Ticket Created",
        description: "Critical database issue reported by David Chen.",
        type: "CREATED",
      },
    ],
  },
];
